name: CI with Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Cache dependencies
      - name: Prime cache cache-eae81e1
        id: prime-cache-eae81e1
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-eae81e1

      # Step 4: Echo cache hit/miss
      - name: Echo cache result
        run: |
          if [ -n "${{ steps.prime-cache-eae81e1.outputs.cache-hit }}" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Step 5: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 6: Run tests
      - name: Run tests
        run: npm test
